### ISSUE TITLE
Write parsers

### ISSUE THREAD

**Issue by lerastromtsova** [revyakinpetr/protabletochki#7]
### Task
Write parsers for the following websites:
- [x] https://protabletky.ru
- [x] https://drugchoice.vrachirf.ru
- [x] https://www.rlsnet.ru

- [x] VK(use API)

### Rules

- Do things in branch **task-7** (it's already created, do `git pull`)
- Start your commit message with `#7:`, so it gets linked to this issue
- Keep your modules in folder `parsers`
- Each module should be a file named `<website_name>_parser.py` (for example, `toneto_parser.py`)
- Each parser should:
1. Take all drugs from `data/drugs_list.json` file
2. For each of the drugs, parse reviews from a website
3. Save reviews to `data/<drug_name>_<website_name>.json` according to the structure:
`[{comment: "", date*: "", author*: "", ...}, ...]`
Comment is the only mandatory field in this structure. You can add other fields if you wish to.
